config/routes.rb
Rails.application.routes.draw do
  
# Home routes  
  root 'pages#home'
  get '/home', to: 'pages#home' 
  
# Recipe routes
  # get '/recipes', to: 'recipes#index' 
  # get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  # post '/recipes', to: 'recipes#create' 
  # get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  # patch '/recipes/:id', to: 'recipes#update' 
  # get 'recipes/:id', to: 'recipes#show', as: 'recipe'
  # delete '/recipes/:id', to: 'recipes#destroy'
  
  
  
   resources :recipes
   
   resources :chefs, except: [:new, :destroy]
   
   get '/register', to: 'chefs#new'
   
   get '/login', to: 'logins#new'
   post '/login', to: 'logins#create'
   get '/logout', to: 'logins#destroy'
   
   get '/contact', to: 'pages#contact' 
   get '/about', to: 'pages#about' 
   
   resources :styles, only: [:new, :create, :show]
   resources :ingredients, only: [:new, :create, :show]
   
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  has_many :recipe_styles, dependent: :destroy
  has_many :styles, through: :recipe_styles
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  validates :chef_id, presence: true
  validates :name, presence: true, length: {minimum: 4, maximum: 50}
  validates :summary, presence: true, length: {minimum: 3, maximum: 200}
  validates :description, presence: true, length: {minimum: 20, maximum: 5000}
  mount_uploader :picture, PictureUploader
  validate :picture
  
  default_scope -> { order(updated_at: :desc) }
  
  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "Should be less than 5MB")
      end
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:edit, :update, :show]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update]
  
  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 6)
  end
  
  def show
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_user
    
    if @recipe.save
      flash[:success] = "Your recipe was created successfully!"
      redirect_to recipes_path
      
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Your recipe was updated successfully!"
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
    
  end
  
  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "The recipe was deleted successfully."
    redirect_to recipes_path
  end
  
  
  private
    def recipe_params
      params.require(:recipe).permit(:name, :summary, :description, :picture, style_ids: [], ingredient_ids: [])
    end 
    
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end
    
    def require_same_user
      if current_user != @recipe.chef and !current_user.admin?
        flash[:danger] = "You can only edit your own recipes!"
        redirect_to recipes_path
      end
    end
    
    def admin_user
      redirect_to recipes_path unless current_user.admin?
    end
    
    
end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class= "row">
  <div class="well col-md-8 col-md-offset-2">
  <%= form_for(@recipe, html: { multipart: true }) do |f| %>
    <%= f.label(:name, "Recipe Name") %>
    <%= f.text_field :name %>
    
    <%= f.label(:summary, "Summary") %>
    <%= f.text_area :summary, rows: 10 %>
    
    <%= f.label(:description, "Description and Steps") %>
    <%= f.text_area :description, rows: 10 %>
    
    <strong>Cuisine:</strong>
 
      <%= f.collection_check_boxes :style_ids, Style.all, :id, :name do |cb| %>
        <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
      <% end %>
    <br/>
    <strong>Ingredients:</strong>
 
      <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb| %>
        <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
      <% end %>

    <br/><br/>
    
    <span class="picture">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </span>
    
    <%= f.submit(@recipe.new_record? ? 'Create Recipe' : 'Edit Recipe', class: "btn btn-success") %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#recipe_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024 /1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.')
    }
  });
</script>

app/views/recipes/edit.html.erb
<div class="home-background">

 <%= render 'shared/page_title', title: "Edit Recipe" %>
    

  <%= render 'form' %>
  

</div>

app/views/recipes/index.html.erb
<div class="recipe-background">
  <%= render 'shared/page_title', title: "All Recipes" %>
    <ul class="nav nav-tabs text-center">
      <li class="active">
        <%= link_to "Recipes", recipes_path %>
      </li>
      <li>
        <%= link_to "Chefs", chefs_path %>
      </li>
    </ul>
<h2> These are recipes from our users.<br/></h2>

</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4 text-center">
    <%= will_paginate %>
  </div>
</div>


<% @recipes.each do |recipe| %>
  <div class="row">
   
      
    <div class="col-md-4">
      <%= image_tag(recipe.picture.url, size: "300x175", class: "gravatar") if recipe.picture? %>
    </div>
  
 
    
    <div class="col-lg-6 well"> 
      <h3><%= link_to recipe.name, recipe_path(recipe) %> </h3>
        <h4><%= recipe.summary %></h4>
        
          <% if recipe.styles.any? %>
          <p>Cuisine: <%= render recipe.styles %></p>
        <% end %>
        
        <!--<% if recipe.ingredients.any? %>-->
        <!--<p>Ingredients: <%= render recipe.ingredients %></p>-->
        <!-- <% end %>-->
      <p>
        <span class="quiet">
          <small>
            Created about <%= time_ago_in_words(recipe.created_at) %> ago.
          </small>
        </span>
        <!-- <span class="quiet">-->
        <!--  <small>-->
        <!--    Updated: <%= time_ago_in_words(recipe.updated_at) %> ago.-->
        <!--  </small>-->
        <!--</span>-->
    </div>

     <div class="col-md-2">
       <section class="chef_info center">
         <%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef) %>
       <h5>Chef: <%= recipe.chef.name %></h5>
       
      </section>
      </div>
    
  </div>  
  <hr/>
<% end %>

<div class="row">
  <div class="col-md-4 col-md-offset-4 text-center">
    <%= will_paginate %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="home-background">

<%= render 'shared/page_title', title: "Create a New Recipe" %>

  <%= render 'form' %>

</div>

app/views/recipes/show.html.erb
<br>
<br>

<%= render 'shared/page_title', title: @recipe.name %>
  
<div class="row">
  <div class="col-md-12">
    
    <!--Left Side-->
    <div class="col-md-7">
      
      <!--Recipe Summary-->
      <div class="row">
        <div class="col-md-12">
          <h3><%= @recipe.summary %></h3>
        </div>
      </div>
      
      <!--Recipe Image-->
      <div class="row">
        <div class="col-md-12 show_recipe">
          <%= image_tag(@recipe.picture.url, size: 100, class: "gravatar") if @recipe.picture? %>
        </div>
      </div>
      
    </div>
    
    <!--Right Side-->
    <div class="col-md-5">
      
      <!--Chef Image-->
      <div class="row">
        <div class="col-md-12 text-center">
          <%= link_to gravatar_for(@recipe.chef, size: 75), chef_path(@recipe.chef) %>
          <h4>Brought to you by Chef <%= @recipe.chef.name %></h4>
        </div>
      </div>
      
      <hr/>
      
      <!--Recipe Details-->
      <div class="row">
        <div class="col-md-12">
          <% if @recipe.styles.any? %>
            <p>Cuisine: <%= render @recipe.styles %></p>
          <% end %>
          <p><b>Recipe:</b></p>
          <%= simple_format(@recipe.description) %>
        </div>
      </div>
      
    </div>
    
    <!--Bottom Buttons-->
    <div class="row">
      <div class="col-md-12">
        
        <!--Return to Recipes Button-->
        <%= link_to "Return to Recipes", recipes_path, class: "btn btn-primary btn-md" %>
        
        <!--Edit Button-->
        <% if logged_in? and (@recipe.chef == current_user || current_user.admin?) %>
          <%= link_to "Edit this Recipe", edit_recipe_path(@recipe), class: "btn btn-success pull-left" %>
        <% end %>    
        
        <!--Delete Button-->
        <% if logged_in? and (@recipe.chef == current_user || current_user.admin?) %>
          <%= link_to "Delete Recipe", @recipe, method: :delete, class: "btn btn-danger pull-left", data: {confirm: "Are you sure that you want to delete this recipe?"} %>
        <% end %>
        
      </div>
    </div>
    
  </div>
</div>