config/routes.rb
Rails.application.routes.draw do
  
# Home routes  
  root 'pages#home'
  get '/home', to: 'pages#home' 
  
# Recipe routes
  # get '/recipes', to: 'recipes#index' 
  # get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  # post '/recipes', to: 'recipes#create' 
  # get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  # patch '/recipes/:id', to: 'recipes#update' 
  # get 'recipes/:id', to: 'recipes#show', as: 'recipe'
  # delete '/recipes/:id', to: 'recipes#destroy'
  
  
  
   resources :recipes
   
   resources :chefs, except: [:new, :destroy]
   
   get '/register', to: 'chefs#new'
   
   get '/login', to: 'logins#new'
   post '/login', to: 'logins#create'
   get '/logout', to: 'logins#destroy'
   
   get '/contact', to: 'pages#contact' 
   get '/about', to: 'pages#about' 
   
   resources :styles, only: [:new, :create, :show]
   resources :ingredients, only: [:new, :create, :show]
   
end

app/views/pages/about.html.erb
<%= render 'shared/page_title', title: "About Us" %>

app/views/pages/contact.html.erb
<%= render 'shared/page_title', title: "Contact Us" %>

app/views/pages/home.html.erb
<body class ="image responsive home-bg">
  <div class ="img-responsive home">
    
    <!--Homepage Main Header-->
    <div class="white jumbotron text-center home">
      <% if logged_in? %>
        
        <!--New Recipe Link-->
        <h1>Show your cooking genius!</h1>
        <h2> Share your recipes with our hungry community.</h2>
        <br/>
        <%= link_to "New Recipe", new_recipe_path, class: "btn btn-lg btn-success" %>
        
      <% else %>
      
        <!--Registration Link-->
        <h1> Fingerlicking Good </h1>
        <h2> Food is better shared.</h2>
        <br/>
        <%= link_to "Join Now", register_path, class: "btn btn-lg btn-warning" %>
        
      <% end %>
    </div>

    <!--Bottom Boxes-->
    <div class="row">
      <div class="col-md-12">
        
        <!--Left Box-->
        <div class="col-md-4 col-md-offset-1 well text-center">
          <h2 class="midrow">Just want to browse?</h2>
          <%= link_to "Browse All Recipes", recipes_path, class: "btn btn-primary btn-small" %>
        </div>
        
        <!--Empty Div-->
        <div class="col-md-2">
        </div>
        
        <% if logged_in? %>  
       
          <!--User Profile Page Link-->
          <div class="col-md-4 col-md-offset-1 well text-center">
            <h2 class="midrow">Manage Your Recipes</h2>
            <%= link_to "Your Recipes", chef_path(current_user), class: "btn btn-primary btn-small" %>
          </div>

        <% else %>
        
          <!--Login Link-->
          <div class="col-md-4  well text-center">
            <h2 class="midrow">Log in to Your Account</h2>
            <%= link_to "Log In", login_path, class: "btn btn-success btn-small" %>
          </div>
          
        <% end %>

        <!--Empty Div-->
        <div class="col-md-12-hide">            ...
        </div>
      
      </div>
    </div>
    
  </div>
</body>