config/routes.rb
Rails.application.routes.draw do
  
# Home routes  
  root 'pages#home'
  get '/home', to: 'pages#home' 
  
# Recipe routes
  # get '/recipes', to: 'recipes#index' 
  # get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  # post '/recipes', to: 'recipes#create' 
  # get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  # patch '/recipes/:id', to: 'recipes#update' 
  # get 'recipes/:id', to: 'recipes#show', as: 'recipe'
  # delete '/recipes/:id', to: 'recipes#destroy'
  
  
  
   resources :recipes
   
   resources :chefs, except: [:new, :destroy]
   
   get '/register', to: 'chefs#new'
   
   get '/login', to: 'logins#new'
   post '/login', to: 'logins#create'
   get '/logout', to: 'logins#destroy'
   
   get '/contact', to: 'pages#contact' 
   get '/about', to: 'pages#about' 
   
   resources :styles, only: [:new, :create, :show]
   resources :ingredients, only: [:new, :create, :show]
   
end

app/views/layouts/_footer.html.erb
<div class="footer"> 
  <p>&copy; Made by Sandra Adams-Hallie. All rights reserved, 2016. </p>
</div>

app/views/layouts/_messages.html.erb
<div class="row text-center">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"> 
      <%= message %>
      <a class="close" data-dismiss="alert">&#215;</a>
      </div>
      
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      
      <!--Responsive navbar-->
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    
      <!--Logo-->
      <%= link_to root_path, class: 'navbar-brand', id: "logo" do %>
       Mrs. Green
      <% end %>
    </div>
    
    <!--Logo contents right-side-->
    <div class="collapse navbar-collapse" id="navbar">
      <div class="nav navbar-nav navbar-right">
        
        <!--Ingredients Button-->
        <!--<ul class="nav_ul_item">-->
        <!--  <li class="dropdown">-->
        <!--    <%= link_to '#', class: "btn btn-default btn-default dropdown-toggle", "data-toggle" => "dropdown" do %>-->
        <!--      Ingredients <b class="caret"></b>-->
        <!--    <% end %>-->
        <!--    <ul class="dropdown-menu">-->
        <!--      <% Ingredient.all.each do |ingredient| %>-->
        <!--        <li><%= link_to ingredient.name, ingredient_path(ingredient) %></li>-->
        <!--      <% end %>-->
        <!--    </ul>-->
        <!--  </li>-->
        <!--</ul>-->
        
        <!--Cuisines Button-->
        <!--<ul class="nav_ul_item">-->
        <!--  <li class="dropdown">-->
        <!--    <%= link_to '#', class: "btn btn-default btn-default dropdown-toggle", "data-toggle" => "dropdown" do %>-->
        <!--      Cuisines <b class="caret"></b>-->
        <!--    <% end %>-->
        <!--    <ul class="dropdown-menu">-->
        <!--      <% Style.all.each do |style| %>-->
        <!--        <li><%= link_to style.name, style_path(style) %></li>-->
        <!--      <% end %>-->
        <!--    </ul>-->
        <!--  </li>-->
        <!--</ul>-->
        
        <% if logged_in? %>
          
          <!--New Recipe Button-->
          <li>
            <%= link_to new_recipe_path do %>
              <span class="glyphicon glyphicon-pencil"></span>&nbsp;New Recipe
            <% end %>
          </li>
          
          <!--Logged In Dropdown Menu-->
          <li class="dropdown">
            <%= link_to '#', class: "dropdown-toggle btn btn-success", id: "user-profile", data:{toggle: 'dropdown'}, role: "button", "aria-expanded" => "false" do %>
              <%= current_user.name %> <b class="caret"></b>
            <% end %>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to chef_path(current_user) do %>
                    <span class="glyphicon glyphicon-user"></span>&nbsp;Profile
                  <% end %>
                </li>
                <li>
                  <%= link_to edit_chef_path(current_user) do %>
                    <span class="glyphicon glyphicon-cog"></span>&nbsp;Settings
                  <% end %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to logout_path do %>
                    <span class="glyphicon glyphicon-log-out"></span>&nbsp;Logout
                  <% end %>
                </li>
              </ul>
          </li>
        
        <% else %>
          
          <!--Login Button-->
          <li>
            <%= link_to login_path do %>
              <span class="glyphicon glyphicon-log-in"></span>&nbsp;Login
            <% end %>
          </li>
          
        <% end %>
        
        <!--About Button-->
        <!--<li>-->
        <!--  <%= link_to about_path do %>-->
        <!--    <span class="glyphicon"></span>&nbsp;About-->
        <!--  <% end %>-->
        <!--</li>-->
        
        <!--Contact Button-->
        <!--<li>-->
        <!--  <%= link_to contact_path do %>-->
        <!--    <span class="glyphicon"></span>&nbsp;Contact-->
        <!--  <% end %>-->
        <!--</li>-->
    
      </div>
    </div>    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mrs. Green</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>
  

   <%= render 'layouts/navigation' %>
   
    <div class="container">
      <!--Flash messages wil pop up here-->
      <%= render 'layouts/messages' %>
      
      <%= yield %>

    
    <%= render 'layouts/footer' %>
    
  </body>
</html>